name: Build debug binaries (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --profile dev --verbose
    - name: Run tests
      run: cargo test --profile dev --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: debug
        path: |
          target/debug/
          !target/debug/*.d
          !target/debug/*.rlib
          !target/debug/deps/
          !target/debug/build/
          !target/debug/incremental/
      